import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../../styles/base.css"  
import "../../styles/components.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { headers } from 'next/headers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const headersList = await headers();
  const pathname = headersList.get('x-pathname') || '';
  const isAdminPage = pathname.startsWith('/admin');
  // 로그인 관련 경로만 배열로 관리
  const authHideFooterPaths = [
    '/auth/login',
    '/auth/email-login',
    '/auth/find-email',
    '/auth/reset-password',
    '/auth/signup',
    '/auth/signup/email',
  ];
  const isAuthHideFooterPage = authHideFooterPaths.some((path) => pathname === path);

  return (
    <html lang="en">
      <body style={{ fontFamily: "Pretendard, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', sans-serif" }}>
        <Header />  
        {children}
        {!isAdminPage && !isAuthHideFooterPage && pathname && pathname !== '/' && <Footer />}
      </body>
    </html>
  );
}
